replicaCount: 1

image:
  repository: your-dockerhub/simplehelm
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  hosts:
    - host: hello.local
      paths:
        - path: /
          pathType: Prefix
